Algoritmo "L03B"
// Disciplina   :[ Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : Progressao aritimética de 100 números! (P.A)
// Autor(a)    : Bernardo Prieto
// Data atual  : 15/09/2023
Var
   contador,resultado:inteiro



Inicio
   contador<-1
   enquanto contador < 101 faca
      resultado<-resultado+contador
      contador<-contador+1
   fimenquanto
   escreval(resultado)


Fimalgoritmo