Algoritmo "L03D"
// Disciplina   : [ Lógica de Programação]
// Professor   : Jailson Costa
// Descrição   : números ímpares de 0 a 20! (ímpares 0 a 20)
// Autor(a)    : Bernardo Prieto
// Data atual  : 15/09/2023
Var
   contador:inteiro



Inicio
   enquanto contador < 21 faca
      se contador mod 2 = 1 entao
         escreval(contador)
      fimse
      contador<-contador+1
   fimenquanto




Fimalgoritmo